// DummyChange
// Login mit Basic Authentication mit korrekten Credentials test@gmx.de:TestPW
// Base64 encoding & decoding: https://www.base64decode.org

### 
POST http://localhost:8080/api/v1/user/create
Content-Type: application/json
Authorization: {{testToken}}

{
    "userMail": "sekoulidis.lukas@icloud.com",
    "userName": "Lukas Sekoulidis",
    "password": "TestPW"
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTWFpbCI6InNla291bGlkaXMubHVrYXNAaWNsb3VkLmNvbSIsImlhdCI6MTY1MzY0Mjg3OX0.iUKF6cDoDGZIo5qaT2FgR2b3IWwhu0LdBCXNLMjeJm4

###
GET http://localhost:8080/api/v1/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTWFpbCI6InNla291bGlkaXMubHVrYXNAaWNsb3VkLmNvbSIsImlhdCI6MTY1NDE3NzkzMn0.3P1Fd3qDOxZLWpKKU1Wh6if7Y2I0ZUMphWOuBHZh1iY


###
# @name loginTest
GET http://localhost:8080/api/v1/login
Authorization: Basic c2Vrb3VsaWRpcy5sdWthc0BpY2xvdWQuY29tOlRlc3RQVw==

@testToken = {{loginTest.response.headers.Authorization}}

// Rufe alle User ab
###
GET http://localhost:8080/api/v1/user
Authorization: {{testToken}}

// Legt ersten User an
###
POST http://localhost:8080/api/v1/user/create
Content-Type: application/json
Authorization: {{testToken}}

{
    "userMail": "stephan@gmx.de",
    "userName": "Stephan",
    "password": "TestPW"
}

// Rufe den User mit userMail test@gmx.de ab. 
###
GET http://localhost:8080/api/v1/user/Stephan
Authorization: {{testToken}}

// Lege zweiten User an
###
POST http://localhost:8080/api/v1/user/create
Content-Type: application/json
Authorization: {{testToken}}

{
    "userMail": "max@muster.de",
    "userName": "Max Muster",
    "password": "maxMuss"
}

// Ändere beim zweiten User den User-Name. Zur Selektion des Users verwende die userID.
###
PUT http://localhost:8080/api/v1/user/update/Manfred
Content-Type: application/json
Authorization: {{testToken}}

{
    "userName": "Udo"
}

// Rufe alle User ab. Es sollten 2 User zurückgegeben werden.
###
GET http://localhost:8080/api/v1/user
Authorization: {{testToken}}

// Lösche den User mit der User-ID manfred
###
DELETE  http://localhost:8080/api/v1/user/delete/Udo
Authorization: {{testToken}}

###
# @name postNoteTest
POST http://localhost:8080/api/v1/note/create
Content-Type: application/json
Authorization: {{testToken}}

{
    "noteTitle": "DasDasDa",
    "noteInput": "Testtesttest"
}

###
@testNoteID =  {{postNoteTest.response.body._id}}

###
# @name postCatTest
POST  http://localhost:8080/api/v1/category/create
Content-Type: application/json
Authorization: {{testToken}}

{
    "categoryTitle": "zzzz"
}

###
GET http://localhost:8080/api/v1/category
Authorization: {{testToken}}

###
@testCategoryID =  {{postCatTest.response.body._id}}
###



DELETE http://localhost:8080/api/v1/note/delete/{{testNoteID}}
Authorization: {{testToken}}

###
PUT http://localhost:8080/api/v1/note/update/{{testNoteID}}
Content-Type: application/json
Authorization: {{testToken}}

{
    "noteTitle": "DieDieDie",
    "noteInput": "Why",
    "categoryID": "Cat2"
}

###
GET http://localhost:8080/api/v1/category/getAll/TestCategory
Content-Type: application/json
Authorization: {{testToken}}

###
GET http://localhost:8080/api/v1/note/myNotes?noteTitle=Derdiedas
Authorization: {{testToken}}

###
GET http://localhost:8080/api/v1/note/myNotes/{{testNoteID}}
Authorization: {{testToken}}